### ISSUE TITLE
ダークモードカラーパレットを適用するとアニメ生放送ページ(一挙放送 放送予定)のデザインがおかしくなる

### ISSUE THREAD

**Issue by chobitsky** [castella-cake/niconico-peppermint-extension#13]
度々お世話になります。

前回はタイムシフトマイページの改善ありがとうございました。
今回は「アニメ生放送(一挙放送 放送予定)」ページの不具合について報告です。

- 該当のページ
https://anime.nicovideo.jp/live/reserved-ikkyo.html?from=nanime_live-reserved_list

以下のように全体的にCSSが崩れてしまっているかもしれません。
フィルタータブの「全て」「今期最新」「一挙放送」などをクリックするとこんな感じになります。
タブを何度もクリックしたり、リロードを繰り返すと直るときもたまにあるのですが基本的には画像のとおりです。
<img src="https://github.com/castella-cake/niconico-peppermint-extension/assets/5998940/7d2d7aa3-3717-4679-9d85-02b66f627d08" width="460px">

該当の予約ページの番組箇所のhtmlソース部分です。
```
<a href="https://live.nicovideo.jp/watch/lv342280256?from=nanime_live-reserved-ikkyo_list" target="_blank" rel="noopener" onclick="NicoGoogleTagManagerDataLayer.push({&quot;event&quot;:&quot;nanime_click_contents&quot;,&quot;event_info&quot;:{&quot;label_detail&quot;:&quot;live-reserved-ikkyo&quot;}});">【ホロスターズ夏休み2023】24時間連続！オリジナル3Dアニメ「スターズこれくしょん！」全61話を一挙放送スペシャル</a>
```

またお手すきの際にでもご確認いただけますと幸いです。

### 利用環境
- Windows11 Home Ver: 22H2
- Google Chrome バージョン: 115.0.5790.171（Official Build）(64 ビット）

**Comment by castella-cake** [comment]
報告ありがとうございます。Nアニメのダークモード対応が未実装のため発生する問題です。
スタイルシートを見てみた感じ比較的容易に実装できそうなので、`1.7.0`でNアニメの部分的なダークモードサポートを追加します

**Comment by castella-cake** [comment]
`1.7.0`で修正。クローズします
報告ありがとうございました！
