### ISSUE TITLE
特定のシリーズをストックするとシリーズストックが開けなくなります

### ISSUE THREAD

**Issue by T5idr3** [castella-cake/niconico-peppermint-extension#34]
## 何が起きたか

一部のシリーズをストックに追加すると、シリーズストックのタブを開くと同時に表示が崩れるためアクセスできなくなります
またダッシュボードにシリーズストックを表示している場合は、拡張機能のアイコンクリックで出るメニュー自体が開きません

## 問題のシリーズリンク

+ [【Escape from Tarkov】キツネとネコさんの脱出劇](https://www.nicovideo.jp/user/39799774/series/450832)

## 設定のエクスポート

```json
{
	"darkmode": "spcolor",
	"dashboardsortlist": [
		{
			"isHidden": false,
			"name": "quickoption"
		},
		{
			"isHidden": true,
			"name": "seriesstock"
		},
		{
			"isHidden": true,
			"name": "nicorepo"
		}
	],
	"enablequicksettingstab": false,
	"enableseriesstock": true,
	"enableseriesstocktab": true,
	"hideeventbanner": true,
	"hidepopup": true,
	"hiderankpagead": true,
	"hidesupporterbutton": "all",
	"playertheme": "mint",
	"quickpaneltipisclosed": true,
	"showseriesstockinpage": true,
	"stockedseries": [
		{
			"seriesID": "450832",
			"seriesName": "【Escape from Tarkov】キツネとネコさんの脱出劇"
		}
	]
}
```

## 動作環境

+ OS: Windows 11 Home バージョン 10.0.22631.3447 (23H2)
+ ブラウザ: Microsoft Edge バージョン 124.0.2478.51 (公式ビルド) (64 ビット)
+ 現在使用中のバージョン: v2.0.0 Manifest V3

**Comment by castella-cake** [comment]
申し訳ないです、報告ありがとうございます！styleの設定方法に問題があったため、修正しました。
近い内にリリースされる`2.0.1`で修正予定です。

**Comment by castella-cake** [comment]
遅れて申し訳ないです、`2.0.1`のリリースで修正しました。
報告ありがとうございました！
