### ISSUE TITLE
ストック中のシリーズの表示される縦サイズに上限が無い様に見える

### ISSUE THREAD

**Issue by rwrwtyr** [castella-cake/niconico-peppermint-extension#5]
//www.nicovideo.jpトップページ左下に表示されるストック中のシリーズのアイコンを押して一覧を開いた際
最大で最新9ストックまでしか表示されず、10ストック以降は画面外へと突き抜けてしまう
もし自身の環境依存でなければ、画面内に収まる高さと縦のスクロールバーを設定して欲しい

後はドラッグ＆ドロップで表示順を簡単に入れ替えられると最高だと思う

**Comment by castella-cake** [comment]
報告ありがとうございます、次のアップデートで修正します
D&Dでの並び替えに関しては自分もつけたいと思っている機能なので、別のIssueに分離しました ( #6 )

**Comment by castella-cake** [comment]
1.1.0でheightに上限を追加し、収まらない場合はスクロールできるように修正しました
報告ありがとうございました！
