### ISSUE TITLE
ダークモードカラーパレットを適用するとタイムシフトページのタイトルが見えなくなる

### ISSUE THREAD

**Issue by chobitsky** [castella-cake/niconico-peppermint-extension#7]
いつも便利に使わせていただいております。
ご対応可能か検討いただきたくissuesにあげさせていただきます。

グローバル設定のダークモードカラーパレットから「SolidBlack」「CyberNight」などどれも一緒なのですが選択すると
タイムシフトページのタイトル部分のタイトル色が黒になってしまいます。
このままだと見にくいので可能であればここのタイトル文字色を明るめの色か白などにしていただけると助かります。
ちなみにマウスオーバーすると青色のリンクとして表示されるので文字は見えるようになります。

以下、該当箇所をChromeDevToolで確認した際のhtmlソースです。
- url
https://www.nicovideo.jp/my/timeshift-reservations?ref=pc_mypage_watchlater

```
<div class="___content-area___kprT6 content-area"><div class="___program-summary___pIxJL program-summary ___program-summary___LY3E3 program-summary" data-role="program-summary" title="見える子ちゃん 全12話一挙放送【ホラーアニメ特集】"></div>
```
<img src="https://github.com/castella-cake/niconico-peppermint-extension/assets/5998940/b3b042ea-e5cd-4533-9ed3-274fdf85a0b7" witdh="480px">

もしかしたら私の環境だけかもしれないのでこちらの問題でしたらこのissueはクローズしちゃってください。

### 利用環境
- Windows11
- Google Chrome バージョン: 114.0.5735.248（Official Build） （64 ビット）

**Comment by castella-cake** [comment]
報告ありがとうございます！`1.6.3`で修正予定です。
これに限らず、ダークモードにはまだ対応していないものが多くあり、地道に潰していくしか方法がないので、
ダークモードのパレットが適用されていない物があったら今後も気軽に報告していただけると助かります

**Comment by castella-cake** [comment]
`1.6.3`で修正。Closeします
報告ありがとうございました！

**Comment by chobitsky** [comment]
無事見やすくなりました！
ご対応ありがとうございました。
